sonar.projectKey=hwesselmann_ranking-info
sonar.organization=hwesselmann

sonar.sources=app,lib,config
sonar.tests=test

sonar.exclusions=app/assets/builds/**,public/packs/**,coverage/**
sonar.javascript.exclusions=app/assets/builds/**,public/packs/**

sonar.ruby.coverage.reportPaths=coverage/coverage.json
