production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  ranking_import:
    class: RankingImportJob
    schedule: <%= ENV.fetch("IMPORT_SCHEDULE", "0 12 * * *") %>
    queue: default

development:
  ranking_import:
    class: RankingImportJob
    schedule: <%= ENV.fetch("IMPORT_SCHEDULE", "0 12 * * *") %>
    queue: default
