name: 'test and sca'

on:
  push:
    branches:
    - '**'
    tags-ignore:
      - '**'

jobs:
  vm-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-use-ruby-ubuntu-latest-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-use-ruby-ubuntu-latest-${{ hashFiles('.ruby-version') }}-
    
    - name: Install build dependencies
      run: |
        gem install bundler:2.5.21
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list 
        sudo apt-get update
        sudo apt-get install -y build-essential nodejs libsqlite3-dev yarn

    - name: Bundle install
      run: |
        bundle config set with 'test'
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Install yarn dependencies
      run: |
        yarn install --check-files

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v9.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        RAILS_ENV: test
      with:
        coverageCommand: bundle exec rails test
        coverageLocations:
          "${{github.workspace}}/coverage/.resultset.json"
