name: 'test and sca'

on:
  push:
    branches:
    - '**'
    tags-ignore:
      - '**'

jobs:
  vm-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'

    - name: Install system dependencies
      run: sudo apt-get install -y --no-install-recommends build-essential libsqlite3-dev

    - name: Install yarn dependencies
      run: yarn install

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v9.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        RAILS_ENV: test
      with:
        coverageCommand: bundle exec rails test
        coverageLocations:
          "${{github.workspace}}/coverage/.resultset.json"
