name: 'test and sca'

on:
  push:
    branches:
    - '**'
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'

    - name: Install system dependencies
      run: sudo apt-get install -y --no-install-recommends build-essential libsqlite3-dev

    - name: Install yarn dependencies
      run: yarn install

    - name: Build assets
      run: bundle exec rails assets:precompile

    - name: Set up database
      run: bundle exec rails db:schema:load

    - name: Run tests
      run: bundle exec rails test

  brakeman:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Install Brakeman
      run: gem install brakeman

    - name: Run Brakeman
      run: brakeman --no-pager -q

  bundler-audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Install bundler-audit
      run: gem install bundler-audit

    - name: Update advisory database
      run: bundle audit update

    - name: Run bundler-audit
      run: bundle audit check
